import Cookies from "js-cookie";
import { jwtDecode } from "jwt-decode";
import React, { forwardRef } from "react";
import { useForm } from "react-hook-form";
import { useTranslations } from "next-intl";
import { zodResolver } from "@hookform/resolvers/zod";

import Input from "@/components/atoms/Input";
import { createSupplier } from "@/lib/api-suppliers";
import { supplierSchema } from "@/schemes/supplierSchema";
import CustomButton from "@/components/atoms/CustomButton";

type SupplierFormData = {
    id: string;
    tenantId: string;
    nit: string;
    name: string;
    phone: string;
    address: string;
};

interface SupplierFormProps {
    onSuccess?: () => void;
    onClose?: () => void;
}

const SupplierForm = forwardRef<HTMLFormElement, SupplierFormProps>(({ onSuccess, onClose }, ref) => {
    const t = useTranslations("supplierForm");
    const createSupplierSchema = supplierSchema(t)

    const {
        register,
        handleSubmit,
        reset,
        formState: { errors },
    } = useForm<SupplierFormData>({
        resolver: zodResolver(createSupplierSchema),
    });

    const onSubmit = async (data: SupplierFormData) => {
        const authToken = Cookies.get("authToken");
        if (!authToken) {
            console.error("No hay authToken");
            throw new Error("Authentication token is missing");
        }
        
        const decoded: any = jwtDecode(authToken);
        const tenantId = decoded.tenantId;
        
        const formData = {
            ...data,
            tenantId,
            id: "", 
        };
        console.log("Datos enviados:", formData);
        
        try {                
            const response = await createSupplier(formData);
            console.log("Respuesta del servidor:", response);

            if (response.status === 201) {
                const responseData = await response.json();
                alert(t("successMessage"));
                reset();
                onSuccess?.();
                onClose?.();
            } else {
                const errorData = await response.json();
                console.log("Error al crear el proveedor:", errorData);
                alert(errorData.message || t("errorMessage"));
            }
        } catch (error) {
            console.error("Error en onSubmit:", error);
            alert(t("connectionError"));
        }   
    };

    return (
        <form ref={ref} onSubmit={handleSubmit(onSubmit)} className="grid grid-cols-2 gap-4">
            <div>
                <label className="text-sm font-semibold text-gray-500">{t("code")}</label>
                <Input placeholder={t("autoGenerated")} type="text" disabled={true} />
            </div>

            <div>
                <label className="text-sm font-semibold text-gray-500">{t("name")}</label>
                <Input 
                    className="text-homePrimary-200 bg-transparent" 
                    placeholder={t("namePlaceholder")}  
                    type="text" 
                    {...register("name")}
                />
                {errors.name && <p className="text-red-500 text-xs">{errors.name.message}</p>}
            </div>

            <div>
                <label className="text-sm font-semibold text-gray-500">{t("nit")}</label>
                <Input 
                    className="text-homePrimary-200 bg-transparent" 
                    placeholder={t("nitPlaceholder")} 
                    type="text" 
                    {...register("nit")}
                />
                {errors.nit && <p className="text-red-500 text-xs">{errors.nit.message}</p>}
            </div>

            <div>
                <label className="text-sm font-semibold text-gray-500">{t("phone")}</label>
                <Input 
                    className="text-homePrimary-200 bg-transparent" 
                    placeholder={t("phonePlaceholder")}  
                    type="text" 
                    {...register("phone")}
                />
                {errors.phone && <p className="text-red-500 text-xs">{errors.phone.message}</p>}
            </div>


            <div>
                <label className="text-sm font-semibold text-gray-500">{t("address")}</label>
                <Input 
                    className="text-homePrimary-200 bg-transparent" 
                    placeholder={t("addressPlaceholder")} 
                    type="text" 
                    {...register("address")}
                />
                {errors.address && <p className="text-red-500 text-xs">{errors.address.message}</p>}
            </div>

            <div className="col-span-2 flex justify-end gap-2 mt-4">
            <div className="col-span-2 flex justify-end gap-2 mt-4">
                <CustomButton text={t("close")} style="border text-white bg-homePrimary hover:bg-blue-500" typeButton="button" onClickButton={onSuccess}  />
                <CustomButton text={t("create")} style="border text-white bg-homePrimary hover:bg-blue-500" typeButton="submit" />
            </div>   
            </div>
        </form>
    );
});

SupplierForm.displayName = "SupplierForm";
export default SupplierForm;