"use client";

import Cookies from "js-cookie"; 
import { jwtDecode } from "jwt-decode";
import { useForm } from "react-hook-form";
import { useTranslations } from "next-intl";
import { zodResolver } from "@hookform/resolvers/zod";
import React, { forwardRef, useState, useEffect } from "react";

import CustomButton from "@/components/atoms/CustomButton";
import { updateProduct } from "@/lib/api-products-status";
import { productSchema } from "@/schemes/productSheme";
import { ProductDAO, SupplierDAO } from "@/types/Api";
import Input from "@/components/atoms/Input";

type ProductFormData = {
  id: string;
  supplierId: string;
  name: string;
  stock: number;
  tax: number;
  purchasePrice: number;
  salePrice: number;
};

export interface ProductFormProps {
    product?: ProductDAO; 
    onSuccess?: () => void;
    onClose?: () => void;
    supplier?: string ;
  }

const ProductFormEdit = forwardRef<HTMLFormElement, ProductFormProps>(
  ({ product, supplier, onSuccess, onClose }, ref) => {

    const t = useTranslations("productEdit");
    const editProductSchema = productSchema(t);

    const {
      register,
      handleSubmit,
      reset,
      setValue,
      formState: { errors },
    } = useForm<ProductFormData>({
      resolver: zodResolver(editProductSchema),
    });

    const [selectedSupplier, setSelectedSupplier] = useState<SupplierDAO>();

    useEffect(() => {
        if (product) {
            reset({
                ...product,
            });
        }
    }, [product, reset]);

    const onSubmit = async (data: ProductFormData) => {
      const authToken = Cookies.get("authToken");
      if (!authToken) {
        console.error("No hay authToken");
        throw new Error(t("authTokenMissing"));
      }
      
      const decoded: any = jwtDecode(authToken);
      const tenantId = decoded.tenantId;

      try {
        const productData: ProductDAO = {
          ...data,
          tenantId,
          supplier: selectedSupplier || ({} as SupplierDAO),
          id: product?.id || "",
        };

        const response = await updateProduct(productData, product?.id || "");

        if (response.ok) {
          alert( product?.id ? t("productUpdated") : t("productCreated"));
          reset();
          onSuccess?.();
        } else {
          const errorData = await response.json();
          console.error(`Error al ${product?.id ? "actualizar" : "crear"} el producto:`, errorData);
          alert(product?.id ? t("updateError") : t("createError"));
        }
      } catch (error) {
        console.error("Error en onSubmit:", error);
        alert(t("connectionError"));
      }
    };

    return (
      <form
        ref={ref}
        onSubmit={handleSubmit(onSubmit)}
        className="grid grid-cols-2 gap-4"
      >
        <div>
          <label className="text-sm font-semibold text-gray-500">
            {t("code")}
          </label>
          <Input
            placeholder={t("autoGenerated")}
            type="text"
            disabled={true}
            {...register("id")}
          />
        </div>

        <div>
          <label className="text-sm font-semibold text-gray-500">
            {t("supplier")}
          </label>
          <Input
              placeholder={t("supplier")}
              type="text"
              disabled={true}
              value={selectedSupplier?.name || product?.supplier?.name || ""}
              onChange={(e) => setSelectedSupplier({ ...selectedSupplier, name: e.target.value } as SupplierDAO)}
          />
        </div>

        <div>
          <label className="text-sm font-semibold text-gray-500">
            {t("name")}
          </label>
          <Input
            placeholder={t("namePlaceholder")}
            type="text"
            {...register("name")}
          />
          {errors.name && (
            <p className="text-red-500 text-xs">{errors.name.message}</p>
          )}
        </div>

        <div>
          <label className="text-sm font-semibold text-gray-500">
            {t("stock")}
          </label>
          <Input
            placeholder={t("stockPlaceholder")}
            type="number"
            {...register("stock", { valueAsNumber: true })}
          />
          {errors.stock && (
            <p className="text-red-500 text-xs">{errors.stock.message}</p>
          )}
        </div>

        <div>
          <label className="text-sm font-semibold text-gray-500">
            {t("tax")}
          </label>
          <Input
            placeholder={t("taxPlaceholder")}
            type="number"
            {...register("tax", { valueAsNumber: true })}
          />
          {errors.tax && (
            <p className="text-red-500 text-xs">{errors.tax.message}</p>
          )}
        </div>

        <div>
          <label className="text-sm font-semibold text-gray-500">
            {t("purchasePrice")}
          </label>
          <Input
            placeholder={t("purchasePricePlaceholder")}
            type="number"
            {...register("purchasePrice", { valueAsNumber: true })}
          />
          {errors.purchasePrice && (
            <p className="text-red-500 text-xs">
              {errors.purchasePrice.message}
            </p>
          )}
        </div>

        <div>
          <label className="text-sm font-semibold text-gray-500">
            {t("salePrice")}
          </label>
          <Input
            placeholder={t("salePricePlaceholder")}
            type="number"
            {...register("salePrice", { valueAsNumber: true })}
          />
          {errors.salePrice && (
            <p className="text-red-500 text-xs">
              {errors.salePrice.message}
            </p>
          )}
        </div>

        <div className="col-span-2 flex justify-end gap-2 mt-4">
          <CustomButton 
            text={t("close")}
            style="border text-white bg-homePrimary hover:bg-blue-500" 
            typeButton="button" 
            onClickButton={onClose || onSuccess}  
          />
          <CustomButton 
            text={
              product?.id ? t("updateProduct") : t("createProduct")
            }
            style="border text-white bg-homePrimary hover:bg-blue-500" 
            typeButton="submit" 
          />
        </div>    
      </form>
    );
  }
);

ProductFormEdit.displayName = "ProductFormEdit";
export default ProductFormEdit;